name: CI/CD Pipeline

on:
  push:
    branches: ['main', 'develop']
  pull_request:
    branches: ['*']

defaults:
  run:
    shell: bash

jobs:
  essentials:
    name: Essentials
    runs-on: [self-hosted]
    steps:
      - uses: actions/checkout@v4
      - uses: ./templates/check_merge
      - uses: ./templates/check_conflicts
      - uses: ./templates/check_draft

  lint:
    name: Linting
    runs-on: [self-hosted]
    needs: [essentials]
    steps:
      - uses: actions/checkout@v4
      - uses: ./templates/lint
